version: '3'
services:
    api:
        build: .
        ports:
            - "5000:5000"
        environment:
            MONGO_HOST: mongo
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"
